### ISSUE TITLE
[Contact] Portfolio and Localization question

### ISSUE THREAD

**Issue by vahidtakro** [JuzouSatoru2/JuzouSatoru2#2]
Hey Alex, very nice template. Can I use it?
if yes, I have another way of localization, we can work on it together.

**Comment by alex289** [comment]
Hey, thanks for asking.

Of course you can use it but please remove my personal information.

The localization thing sounds interesting but I'm afraid this will be removed because the new next app directory doesn't support localization out of the box. So we have to build it our own.
Anyways, whats your idea?

**Comment by vahidtakro** [comment]
Thanks,
What I meant was about [Sanity localization](https://www.sanity.io/docs/localization) and MDX editor. 
with your template, let's say you want to have same slug for both languages, just like website.com/new-post for English, and website.com/de/new-post for German. How this can be possible?

so through the Sanity localization, there should be a way to fetch the translation depend on the selected local. What my blog is doing now is this, it fetch the data from markdown files, but as I'm planning to move to Sanity, I don't know how to build this.

**Comment by alex289** [comment]
Sounds very cool. I will definitely have a look into this

**Comment by vahidtakro** [comment]
We can also work on it together if you're interested.

**Comment by alex289** [comment]
Sure, what do you have in mind?
